spring:
  cloud:
    gcp:
      credentials:
        location: classpath:/fullstackapplications.json
  data:
    mongodb:
      uri: ${MENU_MONGO_URL:mongodb://localhost:27071/menu}
  kafka:
    topic: "menu-created-event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties[request.timeout.ms]: 600000
    admin:
      properties:
        bootstrap-servers: kafka-service:9092
    bootstrap-servers: kafka-service:9092

server:
  port: 8081

bucket_name: ${BUCKET_NAME:""}
